### PR TITLE
Tnw clone

### PR DESCRIPTION
**Pull request by codesalley**
https://thenextweb.com/ clone with html and css ony. i used the css flex-box and grid to structure and position elements on the page. use the advantage of max-width to container the page and the images. With media queries the page is responsive on both mobile tablet and desktop.

### CODE REVIEW

**Comment by MuriloRoque** [comment]
## Status: Invalid :red_circle: 

### Hello @juxsalley and @mahtsham :wave: 

### Unfortunately, I need to invalidate your project submission because of the following reasons:

- [ ] You did not provide a description to the Pull Request, please edit the description and write about what you did in the project.

Kindly make the requested changes and submit them for another review, please :pray: 

I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Comment by codesalley** [comment]
https://thenextweb.com/ clone with html and css ony. i used the css flex-box and grid to structure and position elements on the page. use the advantage of max-width to container the page and the images. With media queries the page is responsive on both mobile tablet and desktop.

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @juxsalley  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [ ] Please, make all the changes as requested by the previous TSE.
* [ ] TWN logo should appear at the leftmost part of the navbar on medium size screen ([link to page](https://thenextweb.com/))
* [ ] The TNW logo in the navbar appears too tiny on small screen sizes.

##### Top 3 articles section

* [ ] It contains 3 articles with an image (link) as a background ([link to page](https://thenextweb.com/))

###### Large version

* [ ] It contains TNW logo at the top left corner of the row ([link to page](https://thenextweb.com/))

###### Medium version changes

* [ ] TWN logo disappears ([link to page](https://thenextweb.com/))
###### Small version changes

* [ ] The three articles are not of equal heights. The first one is smaller.

### Make the requested changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by codesalley** [comment]
all suggestions  by TSE has been fixed

**Review by arslanbisharat — APPROVED** [review]
# Approved :smile: 

Hello Developer :wave:

I just reviewed your project and I am very happy to inform you that your project is approved.
Congratulations on achieving this milestone in your career. :clap:


_I am looking forward to seeing your next project._

Stay safe and give me a smile 😇

### Happy Coding
------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Pull request merged**
